### ISSUE TITLE
install.php scrie configuratia chiar daca nu sunt trecute datele la baza de date

### ISSUE THREAD

**Issue by hktr92** [PandioCMS/metin2cms-1x#1]
Instaland Metin2CMS v1.14 pe un webhost, am dat click pe butonul "continua" pana la finalizarea instalarii. In mod surprinzator, instalarea a reusit cu succes, chiar daca nu am trecut nimic in input-urile pentru conectarea la serverul mysql.

Pasi pentru reproducere:
- La instalarea standard, dai click pe "continua" pana la finalizarea instalarii.
- La pasul 2 apare mesaj: "Nu mă pot conecta la baza de date a serverului." dar in acelasi timp si "Configurația a fost scrisă!", putandu-se continua instalarea la urmatorul pas.

Propunere pentru reparare:
- Verifica daca toate input-urile sunt corect scrise (adaugand `required` in HTML).
- Verifica din PHP daca toate input-urile sunt folosite.
- Verifica conexiunea la baza de date. Daca s-a putut conecta, continua mai departe. Daca nu, buton spre pasul anterior.

Pentru rezolvarea problemei se va ocupa Ionut. Dupa rezolvarea bug-ului, se vor cauta si altele si pe urma se va realiza un update la versiunea 1.15. Pentru urmarirea progresului, cititi [acest Gist](https://gist.github.com/hackmylife92/a96b3fdbcfc03d8db4b5)

**Comment by IonutPopescuRO** [comment]
Totul a fost rezolvat.
