### ISSUE TITLE
install.php: alegerea utilizatorului pentru baze de date multiple

### ISSUE THREAD

**Issue by hktr92** [PandioCMS/metin2cms-1x#2]
![Optiunile de configuratie](https://scontent-ams2-1.xx.fbcdn.net/hphotos-xfl1/v/t34.0-12/11944893_1192916577467192_1162791055_n.jpg?oh=288ad7ddf1f60641556a19dc781502c8&oe=55E8EED3)

Propun sa aiba loc urmatoarele schimbari majore la aceasta sectiune:
- Schimbarea numelui de la input. Fiecare input sa aiba un nume specific si usor de inteles pentru altii. (de ex: in loc de SQL-Server sa fie Server SQL)
- Daca input-utile de la "Baza de date CMS" sunt null, atunci: baza de date Metin2CMS se creeaza in mod automat pe serverul de Metin2, iar daca a esuat, notificare ca sa se creeze manual. In caz contrar, face check pentru validarea datelor.

Pentru implementarea celui de-al doilea element din lista, ma gandesc ca trebuie modificat codul sursa astfel:
- inc/config.php: `$use_single_db = true;`
- inc/security.php:

```
$sqlServ = new mysqli(SQL_HOST,  SQL_USER,  SQL_PASS);
$sqlHp = is_bool($use_single_db) && $use_single_db ? $sqlServ : new mysqli(SQL_HP_HOST,  SQL_HP_USER,  SQL_HP_PASS);
```

In acest caz, modificarile pentru acest feature se reduc drastic si va fi compatibil cu un singur link la baza de date mysql. ($sqlHp si $sqlServ se identifica cu aceeasi valoare, dar nume de variabila diferita). 

Modificarile pe care le vei face raman la latitudinea ta :smile:

**Comment by IonutPopescuRO** [comment]
Nu cred ca este necesara o astfel de modificare la versiunea 1.xx, aceasta va fii implementata la versiunea 2.0 .

**Comment by hktr92** [comment]
Mkay, atunci renuntam la acest issue :smiley:
